// <auto-generated/>
#pragma warning disable CS0618
using DocumentAPI.Client.Documents.Item.Content;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DocumentAPI.Client.Documents.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \documents\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DocumentsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The content property</summary>
        public global::DocumentAPI.Client.Documents.Item.Content.ContentRequestBuilder Content
        {
            get => new global::DocumentAPI.Client.Documents.Item.Content.ContentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DocumentAPI.Client.Documents.Item.DocumentsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DocumentsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/documents/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DocumentAPI.Client.Documents.Item.DocumentsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DocumentsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/documents/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
