# Default endpoint address for local testing
@authority=http://localhost:5222

### Get health status of the service
GET {{authority}}/health
Content-Type: text/plain

### Get OpenAPI specification document
GET {{authority}}/swagger/v1/swagger.json
Content-Type: text/plain
