// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DocumentAPI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UnauthorizedError_code
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "UNAUTHORIZED")]
        #pragma warning disable CS1591
        UNAUTHORIZED,
        #pragma warning restore CS1591
    }
}
