// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DocumentAPI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UnhealthyStatus_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Unhealthy")]
        #pragma warning disable CS1591
        Unhealthy,
        #pragma warning restore CS1591
    }
}
